workflows:
  default:
    name: Default Workflow
    environment:
      flutter: stable
    scripts:
      - name: Full Clean and get dependencies
        script: |
          flutter clean
          rm -rf pubspec.lock
          # مسح ذاكرة Gradle المخفية التي قد تحتوي على الخطأ
          rm -rf android/.gradle
          flutter pub get
      - name: Build Android APK
        script: |
          flutter build apk --release
    artifacts:
      - build/**/outputs/apk/**/*.apk
